# Generated by Django 5.0 on 2023-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Hair'), ('N', 'Nails'), ('F', 'Face')], max_length=2),
        ),
    ]
