# Generated by Django 3.0.5 on 2023-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
