# Generated by Django 5.0 on 2023-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_guest_id_orderitem_guest_id_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
