# Generated by Django 5.0 on 2023-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
