# Generated by Django 3.0.5 on 2023-12-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_booking_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
