# Generated by Django 5.0 on 2023-12-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_country_delete_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
